// Conversion route data for SEO landing pages
export interface ConversionRoute {
  slug: string;
  from: string;
  to: string;
  fromExt: string;
  toExt: string;
  mediaType: "video" | "audio" | "image";
  title: string;
  metaDescription: string;
  h1: string;
  description: string;
  steps: string[];
  faq: { q: string; a: string }[];
}

export const CONVERSION_ROUTES: ConversionRoute[] = [
  {
    slug: "convert-mp4-to-mp3",
    from: "MP4", to: "MP3", fromExt: "mp4", toExt: "mp3",
    mediaType: "video",
    title: "Convert MP4 to MP3 Online Free — Quick Convert Pros",
    metaDescription: "Convert MP4 video to MP3 audio instantly for free. No upload needed — files are processed in your browser. Fast, private, and secure.",
    h1: "Convert MP4 to MP3",
    description: "Extract audio from any MP4 video file and save it as MP3. Perfect for saving music, podcasts, or audio from video recordings. Everything runs in your browser — your files never leave your device.",
    steps: ["Upload your MP4 video file", "MP3 format is auto-selected", "Click Convert and download your MP3"],
    faq: [
      { q: "Does converting MP4 to MP3 lose quality?", a: "The audio quality depends on the original MP4 file. Our converter preserves the original audio bitrate for the best possible MP3 output." },
      { q: "How long does MP4 to MP3 conversion take?", a: "Most files convert in under 30 seconds. Larger files may take a bit longer since everything is processed locally in your browser." },
      { q: "Can I convert MP4 to MP3 on mobile?", a: "Yes! Quick Convert Pros works on any device with a modern browser — phones, tablets, and desktops." },
    ],
  },
  {
    slug: "convert-video-to-mp3",
    from: "Video", to: "MP3", fromExt: "video", toExt: "mp3",
    mediaType: "video",
    title: "Convert Video to MP3 Online Free — Quick Convert Pros",
    metaDescription: "Extract MP3 audio from any video file for free. Supports MP4, WebM, MOV, AVI, MKV. No sign-up, processed in your browser.",
    h1: "Convert Video to MP3",
    description: "Extract MP3 audio from any video format — MP4, WebM, MOV, AVI, MKV, and more. Ideal for saving music, lectures, or podcasts from video files.",
    steps: ["Upload any video file", "MP3 is selected as output", "Click Convert and download"],
    faq: [
      { q: "What video formats can I convert to MP3?", a: "We support MP4, WebM, MOV, AVI, MKV, FLV, and most other common video formats." },
      { q: "Is there a file size limit?", a: "You can convert files up to 500MB. For larger files, consider using desktop software." },
    ],
  },
  {
    slug: "convert-webm-to-mp4",
    from: "WebM", to: "MP4", fromExt: "webm", toExt: "mp4",
    mediaType: "video",
    title: "Convert WebM to MP4 Online Free — Quick Convert Pros",
    metaDescription: "Convert WebM videos to MP4 format instantly. Free, no upload — browser-based conversion. Compatible with all devices.",
    h1: "Convert WebM to MP4",
    description: "Convert WebM videos to the universally compatible MP4 format. Great for sharing videos that were recorded in WebM on platforms that require MP4.",
    steps: ["Upload your WebM file", "Select MP4 as output format", "Click Convert and download your MP4"],
    faq: [
      { q: "Why convert WebM to MP4?", a: "MP4 is the most widely supported video format across all devices, social media platforms, and video players. WebM may not play on some older devices." },
      { q: "Does conversion reduce video quality?", a: "Our converter maintains the original video quality during conversion. The output MP4 will look the same as your WebM source." },
    ],
  },
  {
    slug: "convert-png-to-jpg",
    from: "PNG", to: "JPG", fromExt: "png", toExt: "jpg",
    mediaType: "image",
    title: "Convert PNG to JPG Online Free — Quick Convert Pros",
    metaDescription: "Convert PNG images to JPG format instantly. Reduce file size while maintaining quality. Free, no upload — processed in your browser.",
    h1: "Convert PNG to JPG",
    description: "Convert PNG images to JPG to reduce file size for web use, email attachments, or social media. JPG compression can dramatically reduce file sizes while maintaining visual quality.",
    steps: ["Upload your PNG image", "JPG format is auto-selected", "Click Convert and download your JPG"],
    faq: [
      { q: "Does PNG to JPG conversion lose quality?", a: "JPG uses lossy compression, so there is a slight quality reduction. However, our converter uses 92% quality which is virtually indistinguishable from the original." },
      { q: "Why convert PNG to JPG?", a: "JPG files are typically 50-80% smaller than PNG files, making them ideal for web pages, emails, and social media where file size matters." },
    ],
  },
  {
    slug: "convert-jpg-to-png",
    from: "JPG", to: "PNG", fromExt: "jpg", toExt: "png",
    mediaType: "image",
    title: "Convert JPG to PNG Online Free — Quick Convert Pros",
    metaDescription: "Convert JPG images to PNG format for transparency support and lossless quality. Free, no sign-up, processed in your browser.",
    h1: "Convert JPG to PNG",
    description: "Convert JPG images to PNG format for transparency support, lossless quality, or web compatibility. PNG is ideal when you need sharp edges, text overlays, or transparent backgrounds.",
    steps: ["Upload your JPG image", "PNG is selected as output", "Click Convert and download your PNG"],
    faq: [
      { q: "Why convert JPG to PNG?", a: "PNG supports transparency and lossless compression, making it ideal for logos, graphics with text, screenshots, and images that need transparent backgrounds." },
      { q: "Will the file be larger?", a: "Yes, PNG files are typically larger than JPG because PNG uses lossless compression. This is the trade-off for better quality and transparency support." },
    ],
  },
  {
    slug: "convert-mp3-to-wav",
    from: "MP3", to: "WAV", fromExt: "mp3", toExt: "wav",
    mediaType: "audio",
    title: "Convert MP3 to WAV Online Free — Quick Convert Pros",
    metaDescription: "Convert MP3 audio to WAV format for lossless quality. Free, no upload — browser-based conversion. Perfect for audio editing.",
    h1: "Convert MP3 to WAV",
    description: "Convert MP3 files to WAV format for audio editing, professional use, or compatibility with software that requires uncompressed audio.",
    steps: ["Upload your MP3 file", "WAV format is auto-selected", "Click Convert and download your WAV"],
    faq: [
      { q: "Why convert MP3 to WAV?", a: "WAV is an uncompressed audio format preferred by audio editors, musicians, and professional software. It provides the highest compatibility for editing." },
      { q: "Will the WAV file be much larger?", a: "Yes, WAV files are significantly larger than MP3 because they're uncompressed. A 5MB MP3 could become a 50MB WAV file." },
    ],
  },
  {
    slug: "convert-mov-to-mp4",
    from: "MOV", to: "MP4", fromExt: "mov", toExt: "mp4",
    mediaType: "video",
    title: "Convert MOV to MP4 Online Free — Quick Convert Pros",
    metaDescription: "Convert MOV videos from iPhone or Mac to MP4 format. Free, instant, browser-based. No software download needed.",
    h1: "Convert MOV to MP4",
    description: "Convert Apple MOV videos to the universally compatible MP4 format. Perfect for iPhone recordings, QuickTime exports, and Mac video files that need to work everywhere.",
    steps: ["Upload your MOV file", "MP4 is selected as output", "Click Convert and download"],
    faq: [
      { q: "Why convert MOV to MP4?", a: "MOV is Apple's format and may not play on Windows, Android, or some web platforms. MP4 is universally supported across all devices and platforms." },
      { q: "Can I convert iPhone videos?", a: "Yes! iPhone records in MOV format by default. Upload your iPhone videos and convert them to MP4 for easy sharing." },
    ],
  },
  {
    slug: "convert-wav-to-mp3",
    from: "WAV", to: "MP3", fromExt: "wav", toExt: "mp3",
    mediaType: "audio",
    title: "Convert WAV to MP3 Online Free — Quick Convert Pros",
    metaDescription: "Convert WAV audio to MP3 to reduce file size. Free, instant, browser-based. No quality loss you can hear.",
    h1: "Convert WAV to MP3",
    description: "Compress WAV audio files to MP3 format to reduce file size by up to 90% while maintaining excellent audio quality.",
    steps: ["Upload your WAV file", "MP3 is selected as output", "Click Convert and download"],
    faq: [
      { q: "How much smaller will my MP3 be?", a: "MP3 files are typically 5-10x smaller than the equivalent WAV. A 50MB WAV might become a 5MB MP3." },
      { q: "Will I hear a difference?", a: "For most listeners, the difference between a high-quality MP3 and WAV is imperceptible, especially for speech and most music." },
    ],
  },
  {
    slug: "convert-png-to-webp",
    from: "PNG", to: "WebP", fromExt: "png", toExt: "webp",
    mediaType: "image",
    title: "Convert PNG to WebP Online Free — Quick Convert Pros",
    metaDescription: "Convert PNG images to WebP for smaller file sizes with transparency. Free, browser-based. Perfect for web optimization.",
    h1: "Convert PNG to WebP",
    description: "Convert PNG images to Google's WebP format for dramatically smaller file sizes while preserving transparency. WebP is the modern standard for web images.",
    steps: ["Upload your PNG image", "Select WebP as output", "Click Convert and download"],
    faq: [
      { q: "What are the benefits of WebP?", a: "WebP images are 25-35% smaller than PNG at equivalent quality, while still supporting transparency. This means faster loading websites." },
      { q: "Do all browsers support WebP?", a: "Yes, all modern browsers (Chrome, Firefox, Safari, Edge) support WebP. Only very old browsers lack support." },
    ],
  },
  {
    slug: "convert-mp4-to-webm",
    from: "MP4", to: "WebM", fromExt: "mp4", toExt: "webm",
    mediaType: "video",
    title: "Convert MP4 to WebM Online Free — Quick Convert Pros",
    metaDescription: "Convert MP4 videos to WebM for web embedding. Free, instant, no upload — processed in your browser.",
    h1: "Convert MP4 to WebM",
    description: "Convert MP4 videos to WebM format, the open web standard for HTML5 video. Ideal for embedding videos on websites with smaller file sizes.",
    steps: ["Upload your MP4 video", "Select WebM as output", "Click Convert and download"],
    faq: [
      { q: "Why use WebM instead of MP4?", a: "WebM is an open format that often produces smaller files for web use. It's natively supported by Chrome, Firefox, and Edge." },
      { q: "Can I embed WebM in HTML?", a: "Yes, WebM works with the HTML5 <video> tag in all modern browsers." },
    ],
  },
  // Additional long-tail conversions
  {
    slug: "convert-jpg-to-webp",
    from: "JPG", to: "WebP", fromExt: "jpg", toExt: "webp",
    mediaType: "image",
    title: "Convert JPG to WebP Online Free — Quick Convert Pros",
    metaDescription: "Convert JPG images to WebP for 30% smaller file sizes. Free, instant, browser-based. Optimize images for web performance.",
    h1: "Convert JPG to WebP",
    description: "Convert JPG images to WebP format for significantly smaller file sizes without visible quality loss. WebP is recommended by Google for faster web pages and better Core Web Vitals.",
    steps: ["Upload your JPG image", "Select WebP as output format", "Click Convert and download your WebP image"],
    faq: [
      { q: "How much smaller is WebP vs JPG?", a: "WebP images are typically 25-34% smaller than equivalent JPEG images at the same visual quality, according to Google's own benchmarks." },
      { q: "Should I use WebP on my website?", a: "Yes! WebP is supported by all modern browsers and is recommended by Google for better page speed scores and SEO rankings." },
    ],
  },
  {
    slug: "convert-webp-to-jpg",
    from: "WebP", to: "JPG", fromExt: "webp", toExt: "jpg",
    mediaType: "image",
    title: "Convert WebP to JPG Online Free — Quick Convert Pros",
    metaDescription: "Convert WebP images to JPG for maximum compatibility. Free, browser-based. No upload needed.",
    h1: "Convert WebP to JPG",
    description: "Convert WebP images to the universally compatible JPG format. Useful when you need to share images with apps or services that don't support WebP yet.",
    steps: ["Upload your WebP image", "JPG is auto-selected as output", "Click Convert and download"],
    faq: [
      { q: "Why convert WebP to JPG?", a: "While WebP is widely supported in browsers, some older apps, email clients, and social platforms may not display WebP images. JPG is universally compatible." },
      { q: "Does it lose quality?", a: "Our converter uses 92% quality setting which produces virtually identical results to the original with minimal file size increase." },
    ],
  },
  {
    slug: "convert-webp-to-png",
    from: "WebP", to: "PNG", fromExt: "webp", toExt: "png",
    mediaType: "image",
    title: "Convert WebP to PNG Online Free — Quick Convert Pros",
    metaDescription: "Convert WebP images to PNG for lossless quality and transparency. Free, instant, processed in your browser.",
    h1: "Convert WebP to PNG",
    description: "Convert WebP images to PNG format for lossless quality, transparency support, and compatibility with image editors that don't support WebP.",
    steps: ["Upload your WebP image", "PNG is selected as output", "Click Convert and download your PNG"],
    faq: [
      { q: "Will converting WebP to PNG increase file size?", a: "Yes, PNG files are typically larger because PNG uses lossless compression. However, you get perfect quality and full transparency support." },
      { q: "When should I use PNG over WebP?", a: "Use PNG when you need to edit the image in software that doesn't support WebP, or when you need guaranteed lossless quality." },
    ],
  },
  {
    slug: "convert-mp4-to-mov",
    from: "MP4", to: "MOV", fromExt: "mp4", toExt: "mov",
    mediaType: "video",
    title: "Convert MP4 to MOV Online Free — Quick Convert Pros",
    metaDescription: "Convert MP4 videos to MOV format for Apple devices. Free, instant, browser-based. Perfect for iMovie and Final Cut Pro.",
    h1: "Convert MP4 to MOV",
    description: "Convert MP4 video files to Apple's MOV format. Ideal for importing into iMovie, Final Cut Pro, or other Apple-native video editing software.",
    steps: ["Upload your MP4 video file", "Select MOV as output format", "Click Convert and download your MOV file"],
    faq: [
      { q: "Why would I need MOV format?", a: "MOV is Apple's native format and works best with iMovie, Final Cut Pro, and other Apple software. Some Apple workflows require MOV files." },
      { q: "Is there quality loss?", a: "No, the conversion preserves your original video and audio quality." },
    ],
  },
  {
    slug: "convert-avi-to-mp4",
    from: "AVI", to: "MP4", fromExt: "avi", toExt: "mp4",
    mediaType: "video",
    title: "Convert AVI to MP4 Online Free — Quick Convert Pros",
    metaDescription: "Convert AVI videos to MP4 for smaller file sizes and universal compatibility. Free, browser-based. No software needed.",
    h1: "Convert AVI to MP4",
    description: "Convert large AVI video files to the modern MP4 format. MP4 offers much smaller file sizes with the same visual quality, and is compatible with every device and platform.",
    steps: ["Upload your AVI video file", "MP4 is selected as output", "Click Convert and download your MP4"],
    faq: [
      { q: "Why convert AVI to MP4?", a: "AVI files are typically very large and use outdated codecs. MP4 uses modern compression (H.264) that produces files 5-10x smaller with the same quality." },
      { q: "Can I share MP4 on social media?", a: "Yes! MP4 is the standard format accepted by YouTube, Instagram, TikTok, Facebook, Twitter, and all other social platforms." },
    ],
  },
  {
    slug: "convert-mkv-to-mp4",
    from: "MKV", to: "MP4", fromExt: "mkv", toExt: "mp4",
    mediaType: "video",
    title: "Convert MKV to MP4 Online Free — Quick Convert Pros",
    metaDescription: "Convert MKV videos to MP4 for universal device compatibility. Free, instant, no upload required.",
    h1: "Convert MKV to MP4",
    description: "Convert MKV video files to the widely compatible MP4 format. Many devices and apps don't support MKV, but MP4 works everywhere — phones, tablets, TVs, and web browsers.",
    steps: ["Upload your MKV video", "MP4 is selected as output format", "Click Convert and download"],
    faq: [
      { q: "Why doesn't my device play MKV?", a: "MKV is a container format that many devices and apps don't natively support. MP4 is universally compatible with phones, tablets, smart TVs, and all video players." },
      { q: "Does converting MKV to MP4 lose subtitles?", a: "The basic conversion preserves video and audio. Embedded subtitles may need to be added separately after conversion." },
    ],
  },
  {
    slug: "convert-flac-to-mp3",
    from: "FLAC", to: "MP3", fromExt: "flac", toExt: "mp3",
    mediaType: "audio",
    title: "Convert FLAC to MP3 Online Free — Quick Convert Pros",
    metaDescription: "Convert FLAC audio to MP3 for smaller file sizes and universal compatibility. Free, browser-based conversion.",
    h1: "Convert FLAC to MP3",
    description: "Convert lossless FLAC audio files to MP3 format. Reduce file sizes by up to 80% while keeping great sound quality. Perfect for portable music players and phone storage.",
    steps: ["Upload your FLAC audio file", "MP3 is selected as output", "Click Convert and download"],
    faq: [
      { q: "How much smaller is MP3 vs FLAC?", a: "An MP3 file is typically 70-80% smaller than the same FLAC file. A 40MB FLAC song becomes roughly an 8MB MP3." },
      { q: "Is there a noticeable quality difference?", a: "For most listeners on standard speakers or earbuds, the difference is imperceptible. Audiophiles with high-end equipment may notice subtle differences." },
    ],
  },
  {
    slug: "convert-ogg-to-mp3",
    from: "OGG", to: "MP3", fromExt: "ogg", toExt: "mp3",
    mediaType: "audio",
    title: "Convert OGG to MP3 Online Free — Quick Convert Pros",
    metaDescription: "Convert OGG Vorbis audio to MP3 for universal playback. Free, instant, browser-based. No software needed.",
    h1: "Convert OGG to MP3",
    description: "Convert OGG Vorbis audio files to the universally compatible MP3 format. OGG is common in games and open-source software, but MP3 works with every device and music player.",
    steps: ["Upload your OGG audio file", "MP3 is selected as output format", "Click Convert and download your MP3"],
    faq: [
      { q: "What is OGG format?", a: "OGG (Vorbis) is an open-source audio format commonly used in games, Linux systems, and web applications. It offers good quality but isn't supported by all players." },
      { q: "Is OGG or MP3 better quality?", a: "At similar bitrates, OGG Vorbis can sound slightly better than MP3. However, MP3 has universal compatibility which is why many people prefer to convert." },
    ],
  },
  {
    slug: "convert-aac-to-mp3",
    from: "AAC", to: "MP3", fromExt: "aac", toExt: "mp3",
    mediaType: "audio",
    title: "Convert AAC to MP3 Online Free — Quick Convert Pros",
    metaDescription: "Convert AAC audio files to MP3 for wider device compatibility. Free, instant, processed in your browser.",
    h1: "Convert AAC to MP3",
    description: "Convert AAC audio files to MP3 format. AAC is common in iTunes and Apple Music downloads, but MP3 has broader compatibility with all devices and music players.",
    steps: ["Upload your AAC audio file", "MP3 is selected as output", "Click Convert and download your MP3"],
    faq: [
      { q: "What's the difference between AAC and MP3?", a: "AAC generally offers better audio quality at the same bitrate as MP3. However, MP3 is more universally supported across devices and software." },
      { q: "Will my iTunes music work after conversion?", a: "If your AAC files are DRM-free (purchased from iTunes after 2009), yes they will convert perfectly to MP3." },
    ],
  },
  {
    slug: "convert-gif-to-png",
    from: "GIF", to: "PNG", fromExt: "gif", toExt: "png",
    mediaType: "image",
    title: "Convert GIF to PNG Online Free — Quick Convert Pros",
    metaDescription: "Convert GIF images to PNG for better quality and transparency. Free, instant, browser-based conversion.",
    h1: "Convert GIF to PNG",
    description: "Convert GIF images to PNG format for higher quality, better color depth, and proper transparency support. PNG offers superior image quality compared to the 256-color GIF format.",
    steps: ["Upload your GIF image", "PNG is auto-selected as output", "Click Convert and download your PNG"],
    faq: [
      { q: "Why convert GIF to PNG?", a: "GIF is limited to 256 colors and uses basic transparency. PNG supports millions of colors and alpha transparency for much better image quality." },
      { q: "What about animated GIFs?", a: "This converter extracts the first frame of an animated GIF. For full animation conversion, you'll need a specialized tool." },
    ],
  },
  {
    slug: "convert-bmp-to-jpg",
    from: "BMP", to: "JPG", fromExt: "bmp", toExt: "jpg",
    mediaType: "image",
    title: "Convert BMP to JPG Online Free — Quick Convert Pros",
    metaDescription: "Convert BMP images to JPG for dramatically smaller file sizes. Free, browser-based. Reduce image size by 90%+.",
    h1: "Convert BMP to JPG",
    description: "Convert uncompressed BMP images to JPG to massively reduce file sizes. BMP files can be 10-50x larger than the equivalent JPG. Perfect for scanning outputs and legacy image files.",
    steps: ["Upload your BMP image", "JPG is selected as output format", "Click Convert and download your compressed JPG"],
    faq: [
      { q: "How much smaller is JPG vs BMP?", a: "JPG files are typically 90-95% smaller than BMP. A 10MB BMP screenshot might become just 500KB as a JPG." },
      { q: "What is BMP used for?", a: "BMP (Bitmap) is an uncompressed image format common in Windows screenshots, older scanners, and legacy applications. It's rarely used on the web due to huge file sizes." },
    ],
  },
  // ── New popular conversions ──
  {
    slug: "convert-mp4-to-gif",
    from: "MP4", to: "GIF", fromExt: "mp4", toExt: "gif",
    mediaType: "video",
    title: "Convert MP4 to GIF Online Free — Quick Convert Pros",
    metaDescription: "Turn MP4 videos into animated GIFs instantly. Free, no upload — browser-based. Perfect for memes, tutorials, and social sharing.",
    h1: "Convert MP4 to GIF",
    description: "Create animated GIFs from MP4 video clips. Perfect for making memes, reaction images, quick tutorials, or sharing short clips on platforms that support GIF but not video.",
    steps: ["Upload your MP4 video", "GIF is selected as output", "Click Convert and download your animated GIF"],
    faq: [
      { q: "How long of a video can I convert to GIF?", a: "We recommend clips under 15 seconds for best results. Longer videos create very large GIF files." },
      { q: "Will the GIF have sound?", a: "No, GIF is an image format and does not support audio. Only the visual content is preserved." },
    ],
  },
  {
    slug: "convert-mp4-to-avi",
    from: "MP4", to: "AVI", fromExt: "mp4", toExt: "avi",
    mediaType: "video",
    title: "Convert MP4 to AVI Online Free — Quick Convert Pros",
    metaDescription: "Convert MP4 video to AVI format. Free browser-based converter. Compatible with legacy media players and editing software.",
    h1: "Convert MP4 to AVI",
    description: "Convert MP4 videos to AVI format for compatibility with older media players, editing software, or DVD authoring tools that require AVI input.",
    steps: ["Upload your MP4 video", "Select AVI as output format", "Click Convert and download your AVI file"],
    faq: [
      { q: "Why would I need AVI format?", a: "AVI is required by some legacy media players, older video editing software, and certain DVD authoring tools." },
      { q: "Is AVI better quality than MP4?", a: "AVI files are typically larger but not necessarily better quality. MP4 uses more efficient compression." },
    ],
  },
  {
    slug: "convert-flv-to-mp4",
    from: "FLV", to: "MP4", fromExt: "flv", toExt: "mp4",
    mediaType: "video",
    title: "Convert FLV to MP4 Online Free — Quick Convert Pros",
    metaDescription: "Convert Flash Video (FLV) to MP4. Free browser-based converter. Play old Flash videos on modern devices.",
    h1: "Convert FLV to MP4",
    description: "Convert Flash Video (FLV) files to modern MP4 format. Flash is no longer supported by browsers — convert your old FLV files to MP4 so they play on any device.",
    steps: ["Upload your FLV video", "MP4 is auto-selected", "Click Convert and download your MP4"],
    faq: [
      { q: "Can I still play FLV files?", a: "Most modern browsers and devices no longer support Flash or FLV. Converting to MP4 ensures universal playback." },
      { q: "Will I lose quality?", a: "The quality of your converted MP4 will match the original FLV. No additional quality loss occurs during conversion." },
    ],
  },
  {
    slug: "convert-m4a-to-mp3",
    from: "M4A", to: "MP3", fromExt: "m4a", toExt: "mp3",
    mediaType: "audio",
    title: "Convert M4A to MP3 Online Free — Quick Convert Pros",
    metaDescription: "Convert M4A audio files to MP3. Free, instant, browser-based. Make Apple audio files compatible with any device.",
    h1: "Convert M4A to MP3",
    description: "Convert M4A (Apple audio) files to universally compatible MP3 format. M4A files from iPhone recordings, iTunes, or Apple Music can be converted for playback on any device.",
    steps: ["Upload your M4A audio file", "MP3 is selected as output", "Click Convert and download your MP3"],
    faq: [
      { q: "What is M4A?", a: "M4A is Apple's audio format, commonly used by iTunes, iPhone voice memos, and Apple Music. It uses AAC encoding in an MPEG-4 container." },
      { q: "Will conversion affect quality?", a: "There is minimal quality loss. Both M4A (AAC) and MP3 are compressed formats. Our converter uses 192kbps for excellent MP3 quality." },
    ],
  },
  {
    slug: "convert-webp-to-gif",
    from: "WebP", to: "GIF", fromExt: "webp", toExt: "gif",
    mediaType: "image",
    title: "Convert WebP to GIF Online Free — Quick Convert Pros",
    metaDescription: "Convert WebP images to GIF format. Free, instant, browser-based. Ensure compatibility with older platforms.",
    h1: "Convert WebP to GIF",
    description: "Convert WebP images to GIF format for compatibility with platforms and tools that don't support WebP. GIF is universally supported across all messaging apps and social platforms.",
    steps: ["Upload your WebP image", "GIF is selected as output", "Click Convert and download your GIF"],
    faq: [
      { q: "Why convert WebP to GIF?", a: "Some older platforms, email clients, and apps don't support WebP. GIF is universally supported everywhere." },
      { q: "Does this work with animated WebP?", a: "This converts the first frame of animated WebP to a static GIF image." },
    ],
  },
  {
    slug: "convert-png-to-bmp",
    from: "PNG", to: "BMP", fromExt: "png", toExt: "bmp",
    mediaType: "image",
    title: "Convert PNG to BMP Online Free — Quick Convert Pros",
    metaDescription: "Convert PNG images to BMP format. Free, instant, browser-based. For legacy software that requires BMP input.",
    h1: "Convert PNG to BMP",
    description: "Convert PNG images to BMP format for use with legacy software, embedded systems, or applications that specifically require uncompressed BMP images.",
    steps: ["Upload your PNG image", "BMP is selected as output", "Click Convert and download your BMP"],
    faq: [
      { q: "When would I need BMP?", a: "BMP is needed by some legacy Windows applications, embedded systems, certain printers, and industrial software." },
      { q: "Will the BMP file be larger?", a: "Yes, significantly. BMP is uncompressed, so files will be much larger than the PNG source." },
    ],
  },
  {
    slug: "convert-gif-to-jpg",
    from: "GIF", to: "JPG", fromExt: "gif", toExt: "jpg",
    mediaType: "image",
    title: "Convert GIF to JPG Online Free — Quick Convert Pros",
    metaDescription: "Convert GIF images to JPG for smaller file sizes. Free, browser-based. Extracts first frame from animated GIFs.",
    h1: "Convert GIF to JPG",
    description: "Convert GIF images to JPG format for smaller file sizes and broader compatibility. For animated GIFs, the first frame is extracted as a static JPG image.",
    steps: ["Upload your GIF image", "JPG is selected as output", "Click Convert and download your JPG"],
    faq: [
      { q: "Can I convert animated GIFs?", a: "Yes, the converter extracts the first frame of an animated GIF and saves it as a JPG image." },
      { q: "Why JPG over GIF?", a: "JPG supports millions of colors (vs GIF's 256) and produces much smaller files for photographic content." },
    ],
  },
  {
    slug: "convert-mp3-to-ogg",
    from: "MP3", to: "OGG", fromExt: "mp3", toExt: "ogg",
    mediaType: "audio",
    title: "Convert MP3 to OGG Online Free — Quick Convert Pros",
    metaDescription: "Convert MP3 audio to OGG Vorbis format. Free, browser-based. Open-source format for web and gaming.",
    h1: "Convert MP3 to OGG",
    description: "Convert MP3 audio files to OGG Vorbis — the open-source audio format preferred for web audio, game development, and Linux applications. Better quality at lower bitrates than MP3.",
    steps: ["Upload your MP3 file", "OGG is selected as output", "Click Convert and download your OGG"],
    faq: [
      { q: "Why use OGG instead of MP3?", a: "OGG Vorbis is open-source (no licensing fees), offers better audio quality at lower bitrates, and is the preferred format for web audio and game development." },
      { q: "What apps support OGG?", a: "OGG is supported by Firefox, Chrome, VLC, Audacity, most Linux media players, and game engines like Unity and Unreal." },
    ],
  },
  {
    slug: "convert-mp3-to-aac",
    from: "MP3", to: "AAC", fromExt: "mp3", toExt: "aac",
    mediaType: "audio",
    title: "Convert MP3 to AAC Online Free — Quick Convert Pros",
    metaDescription: "Convert MP3 to AAC for better quality at smaller file sizes. Free, browser-based. Perfect for Apple devices.",
    h1: "Convert MP3 to AAC",
    description: "Convert MP3 files to AAC for better audio quality at the same or smaller file sizes. AAC is the default audio format for Apple devices, YouTube, and most streaming platforms.",
    steps: ["Upload your MP3 file", "AAC is selected as output", "Click Convert and download your AAC"],
    faq: [
      { q: "Is AAC better than MP3?", a: "Yes, AAC generally provides better audio quality than MP3 at the same bitrate, especially at lower bitrates." },
      { q: "Do all devices play AAC?", a: "AAC is supported by Apple devices, Android, most modern media players, and all major streaming platforms." },
    ],
  },
  {
    slug: "convert-webm-to-mp3",
    from: "WebM", to: "MP3", fromExt: "webm", toExt: "mp3",
    mediaType: "video",
    title: "Convert WebM to MP3 Online Free — Quick Convert Pros",
    metaDescription: "Extract MP3 audio from WebM videos. Free, browser-based. Perfect for saving audio from web recordings.",
    h1: "Convert WebM to MP3",
    description: "Extract audio from WebM videos and save as MP3. WebM is commonly used for web recordings, screen captures, and browser-based video. Get just the audio track quickly.",
    steps: ["Upload your WebM video", "MP3 is selected as output", "Click Convert and download your MP3"],
    faq: [
      { q: "What is WebM?", a: "WebM is Google's open video format widely used for web video, browser recordings, and screen captures." },
      { q: "Can I extract audio from any WebM?", a: "Yes, as long as the WebM file contains an audio track, our converter will extract it as MP3." },
    ],
  },
  {
    slug: "convert-mov-to-mp3",
    from: "MOV", to: "MP3", fromExt: "mov", toExt: "mp3",
    mediaType: "video",
    title: "Convert MOV to MP3 Online Free — Quick Convert Pros",
    metaDescription: "Extract MP3 audio from MOV videos. Free, browser-based. Perfect for iPhone video audio extraction.",
    h1: "Convert MOV to MP3",
    description: "Extract audio from MOV videos (commonly from iPhones and Macs) and save as MP3. Perfect for getting audio from phone recordings, interviews, or presentations.",
    steps: ["Upload your MOV video", "MP3 is selected as output", "Click Convert and download your MP3"],
    faq: [
      { q: "Can I convert iPhone videos to MP3?", a: "Yes! iPhones record video in MOV format. Upload your iPhone video and extract the audio as MP3." },
      { q: "How fast is MOV to MP3?", a: "Audio extraction is fast since we skip video processing. Most files convert in under 30 seconds." },
    ],
  },
  {
    slug: "convert-flac-to-wav",
    from: "FLAC", to: "WAV", fromExt: "flac", toExt: "wav",
    mediaType: "audio",
    title: "Convert FLAC to WAV Online Free — Quick Convert Pros",
    metaDescription: "Convert FLAC audio to WAV format. Free, browser-based. Lossless conversion for audio editing and production.",
    h1: "Convert FLAC to WAV",
    description: "Convert FLAC files to WAV for compatibility with audio editing software, DAWs, and professional production tools that prefer uncompressed WAV input.",
    steps: ["Upload your FLAC file", "WAV is selected as output", "Click Convert and download your WAV"],
    faq: [
      { q: "Is FLAC to WAV lossless?", a: "Yes! Both FLAC and WAV are lossless formats. FLAC is compressed losslessly, so converting to WAV produces an identical audio stream." },
      { q: "Why convert FLAC to WAV?", a: "Some audio editing software and hardware players only support WAV. WAV is also the standard for CD burning." },
    ],
  },
  {
    slug: "convert-wav-to-ogg",
    from: "WAV", to: "OGG", fromExt: "wav", toExt: "ogg",
    mediaType: "audio",
    title: "Convert WAV to OGG Online Free — Quick Convert Pros",
    metaDescription: "Convert WAV to OGG Vorbis for smaller files with great quality. Free, browser-based. Ideal for web and games.",
    h1: "Convert WAV to OGG",
    description: "Convert large WAV files to compact OGG Vorbis format. Perfect for web audio, game sound effects, and Linux applications. Dramatically reduce file size while maintaining quality.",
    steps: ["Upload your WAV file", "OGG is selected as output", "Click Convert and download your OGG"],
    faq: [
      { q: "How much smaller is OGG vs WAV?", a: "OGG files are typically 80-90% smaller than WAV while maintaining excellent perceived audio quality." },
      { q: "Is OGG good for games?", a: "Yes! OGG Vorbis is the preferred audio format for most game engines due to its small size and open-source license." },
    ],
  },
  {
    slug: "convert-mp4-to-mkv",
    from: "MP4", to: "MKV", fromExt: "mp4", toExt: "mkv",
    mediaType: "video",
    title: "Convert MP4 to MKV Online Free — Quick Convert Pros",
    metaDescription: "Convert MP4 video to MKV container format. Free, browser-based. MKV supports multiple audio and subtitle tracks.",
    h1: "Convert MP4 to MKV",
    description: "Convert MP4 videos to MKV (Matroska) container format. MKV supports multiple audio tracks, subtitles, and chapters — ideal for archiving and media libraries.",
    steps: ["Upload your MP4 video", "MKV is selected as output", "Click Convert and download your MKV"],
    faq: [
      { q: "What is MKV?", a: "MKV (Matroska) is a flexible container format that can hold unlimited video, audio, subtitle tracks and metadata in a single file." },
      { q: "Is MKV better than MP4?", a: "MKV is more flexible (supports more codecs and tracks) but less universally compatible than MP4. It's preferred for media libraries." },
    ],
  },
  {
    slug: "convert-webp-to-bmp",
    from: "WebP", to: "BMP", fromExt: "webp", toExt: "bmp",
    mediaType: "image",
    title: "Convert WebP to BMP Online Free — Quick Convert Pros",
    metaDescription: "Convert WebP images to BMP format. Free, instant, browser-based. For legacy software compatibility.",
    h1: "Convert WebP to BMP",
    description: "Convert WebP images to uncompressed BMP format for use with legacy applications and systems that don't support modern image formats.",
    steps: ["Upload your WebP image", "BMP is selected as output", "Click Convert and download your BMP"],
    faq: [
      { q: "When would I need BMP from WebP?", a: "When working with older Windows software, embedded systems, or specific industrial applications that only accept BMP input." },
    ],
  },
  {
    slug: "convert-jpg-to-gif",
    from: "JPG", to: "GIF", fromExt: "jpg", toExt: "gif",
    mediaType: "image",
    title: "Convert JPG to GIF Online Free — Quick Convert Pros",
    metaDescription: "Convert JPG images to GIF format. Free, browser-based. Create static GIFs for messaging and web use.",
    h1: "Convert JPG to GIF",
    description: "Convert JPG photos to GIF format for use in messaging apps, forums, and older web platforms that work best with GIF images.",
    steps: ["Upload your JPG image", "GIF is selected as output", "Click Convert and download your GIF"],
    faq: [
      { q: "Will the GIF be animated?", a: "No, converting a static JPG produces a static GIF image. To create animated GIFs, you need a video source." },
      { q: "Why would I use GIF over JPG?", a: "GIF is sometimes preferred for simple graphics, logos with few colors, or when a platform specifically requires GIF format." },
    ],
  },
  {
    slug: "convert-jpg-to-bmp",
    from: "JPG", to: "BMP", fromExt: "jpg", toExt: "bmp",
    mediaType: "image",
    title: "Convert JPG to BMP Online Free — Quick Convert Pros",
    metaDescription: "Convert JPG images to BMP format. Free, browser-based. For legacy software and printing needs.",
    h1: "Convert JPG to BMP",
    description: "Convert JPG images to uncompressed BMP format. Useful for legacy software, specific printing workflows, and applications that require uncompressed image input.",
    steps: ["Upload your JPG image", "BMP is selected as output", "Click Convert and download your BMP"],
    faq: [
      { q: "Why convert JPG to BMP?", a: "Some legacy applications, embedded systems, and industrial printers only accept BMP format." },
    ],
  },
  {
    slug: "convert-gif-to-webp",
    from: "GIF", to: "WebP", fromExt: "gif", toExt: "webp",
    mediaType: "image",
    title: "Convert GIF to WebP Online Free — Quick Convert Pros",
    metaDescription: "Convert GIF images to WebP for smaller files and better quality. Free, browser-based. Modern format for the web.",
    h1: "Convert GIF to WebP",
    description: "Convert GIF images to WebP for dramatically smaller file sizes. WebP provides better compression and quality than GIF — perfect for web optimization.",
    steps: ["Upload your GIF image", "WebP is selected as output", "Click Convert and download your WebP"],
    faq: [
      { q: "How much smaller is WebP vs GIF?", a: "WebP images are typically 30-50% smaller than equivalent GIF images while maintaining the same or better visual quality." },
      { q: "Do all browsers support WebP?", a: "Yes, all modern browsers (Chrome, Firefox, Safari, Edge) now support WebP natively." },
    ],
  },
  {
    slug: "convert-bmp-to-png",
    from: "BMP", to: "PNG", fromExt: "bmp", toExt: "png",
    mediaType: "image",
    title: "Convert BMP to PNG Online Free — Quick Convert Pros",
    metaDescription: "Convert BMP to PNG for much smaller files with lossless quality. Free, instant, browser-based.",
    h1: "Convert BMP to PNG",
    description: "Convert BMP images to PNG for dramatically smaller files with lossless compression. PNG preserves full quality while being far more compact than BMP.",
    steps: ["Upload your BMP image", "PNG is selected as output", "Click Convert and download your PNG"],
    faq: [
      { q: "Is BMP to PNG lossless?", a: "Yes! Both BMP and PNG are lossless, so no quality is lost. PNG just compresses more efficiently." },
      { q: "How much smaller is PNG vs BMP?", a: "PNG files are typically 50-80% smaller than BMP while maintaining identical image quality." },
    ],
  },
  {
    slug: "convert-bmp-to-webp",
    from: "BMP", to: "WebP", fromExt: "bmp", toExt: "webp",
    mediaType: "image",
    title: "Convert BMP to WebP Online Free — Quick Convert Pros",
    metaDescription: "Convert BMP to WebP for massive file size reduction. Free, instant, browser-based. Modern web format.",
    h1: "Convert BMP to WebP",
    description: "Convert large BMP images to compact WebP format. WebP offers the best compression for web images — reduce BMP file sizes by 95%+ while maintaining excellent quality.",
    steps: ["Upload your BMP image", "WebP is selected as output", "Click Convert and download your WebP"],
    faq: [
      { q: "How much smaller is WebP vs BMP?", a: "WebP files are typically 95%+ smaller than BMP. A 10MB BMP might become just 200KB as WebP." },
    ],
  },
];

export function getConversionBySlug(slug: string): ConversionRoute | undefined {
  return CONVERSION_ROUTES.find((r) => r.slug === slug);
}
